-- MySQL Script generated by MySQL Workbench
-- Mon Mar 11 10:02:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema car_dealership
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car_dealership
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_dealership` DEFAULT CHARACTER SET utf8 ;
USE `car_dealership` ;

-- -----------------------------------------------------
-- Table `car_dealership`.`dim_cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_dealership`.`dim_cars` (
  `VIN` INT NOT NULL,
  `manufacturer` VARCHAR(45) NULL,
  `model` VARCHAR(45) NULL,
  `year` YEAR(4) NULL,
  `color` VARCHAR(10) NULL,
  PRIMARY KEY (`VIN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_dealership`.`fact_invoices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_dealership`.`fact_invoices` (
  `invoice_number` INT NOT NULL,
  `date` VARCHAR(45) NULL,
  `VIN` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`invoice_number`, `VIN`, `staff_id`, `customer_id`),
  INDEX `fk_invoices_cars1_idx` (`VIN` ASC) VISIBLE,
  CONSTRAINT `fk_invoices_cars1`
    FOREIGN KEY (`VIN`)
    REFERENCES `car_dealership`.`dim_cars` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_dealership`.`dim_customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_dealership`.`dim_customers` (
  `customer_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `phone number` VARCHAR(15) NULL,
  `email` VARCHAR(45) NULL,
  `addres` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `state_province` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `zip_postal_code` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `fk_customers_invoices1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `car_dealership`.`fact_invoices` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_dealership`.`dim_salesperson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_dealership`.`dim_salesperson` (
  `staff_id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `store` VARCHAR(45) NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_dealership`.`dim_staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_dealership`.`dim_staff` (
  `staff_id` INT NOT NULL,
  PRIMARY KEY (`staff_id`),
  CONSTRAINT `fk_dim_staff_invoices`
    FOREIGN KEY (`staff_id`)
    REFERENCES `car_dealership`.`fact_invoices` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dim_staff_salesperson1`
    FOREIGN KEY (`staff_id`)
    REFERENCES `car_dealership`.`dim_salesperson` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
